fast_execute_script:            # 接口名称，用于测试使用
    method: POST
    description: 快速执行脚本
    dependencies: []            # 依赖为空，表示是根接口
    args:
        bk_biz_id: 0
        bk_cloud_id: 0
        account: root
        script_content: ZWNobyBoZWxsbw==            # echo hello

get_job_instance_log:            # 接口名称，用于测试使用
    method: POST
    description: 查询执行脚本结果
    dependencies: ["fast_execute_script"]            # 依赖为空，表示是根接口
    args:
        bk_biz_id: 0
        bk_cloud_id: 0


